name: Read JWT on Pull Request to Main

on:
  pull_request:
    branches:
      - main

jobs:
  decode-jwt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Extract JWT Header and Payload
        run: |
          import os
          import base64
          import json

          def decode_base64(data):
              """Decode base64, padding being optional."""
              missing_padding = len(data) % 4
              if missing_padding:
                  data += '='* (4 - missing_padding)
              return base64.urlsafe_b64decode(data)

          def extract_jwt_parts(jwt):
              header, payload, _ = jwt.split('.')
              header_decoded = json.loads(decode_base64(header))
              payload_decoded = json.loads(decode_base64(payload))
              return header_decoded, payload_decoded

          # Path to the JWT file within the repository
          jwt_file_path = 'web/.well-known/ato/ato.jwt'
          try:
              with open(jwt_file_path, 'r') as file:
                  jwt_token = file.read().strip()
                  header, payload = extract_jwt_parts(jwt_token)
                  print("JWT Header:", json.dumps(header, indent=2))
                  print("JWT Payload:", json.dumps(payload, indent=2))
                  # If you need to use the header and payload in further steps, 
                  # you could set them as environment variables or output them
                  # to use them in subsequent steps
          except FileNotFoundError:
              print("The file was not found.")
          except Exception as e:
              print(f"An error occurred: {e}")

        shell: python
