name: Read JWT and Validate Availability

on:
  pull_request:
    branches:
      - main

jobs:
  validate-availability:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install jq
        run: sudo apt-get install jq

      - name: Validate JWT and Check Availability
        env:
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
          CHECKLY_ACCOUNT: ${{ secrets.CHECKLY_ACCOUNT }}
          CHECKID : ${{ secrets.CHECKID}}
        run: |
          # Decode JWT and extract the availability
          JWT_CONTENT=$(cat web/.well-known/ato/ato.jwt)
          JWT_PAYLOAD=$(echo $JWT_CONTENT | cut -d "." -f 2)

          # Add padding to JWT_PAYLOAD for base64 decoding
          REM=$((${#JWT_PAYLOAD} % 4))
          if [ $REM -eq 2 ]; then JWT_PAYLOAD="${JWT_PAYLOAD}=="
          elif [ $REM -eq 3 ]; then JWT_PAYLOAD="${JWT_PAYLOAD}="
          fi

          # Translate base64url to base64
          JWT_PAYLOAD=$(echo $JWT_PAYLOAD | tr '_-' '/+')

          # Output the padded and translated JWT payload
          echo "Padded and Translated JWT Payload: $JWT_PAYLOAD"

          # Decode Base64
          JWT_PAYLOAD_DECODED=$(echo $JWT_PAYLOAD | base64 -d)
          echo "Decoded JWT Payload: $JWT_PAYLOAD_DECODED"

          JWT_AVAILABILITY=$(echo $JWT_PAYLOAD_DECODED | jq -r '.availability')

          # Call the API
          API_RESPONSE=$(curl -s \
                          --header "Authorization: Bearer $AUTHORIZATION" \
                          --header "x-checkly-account: $CHECKLY_ACCOUNT" \
                          "https://api.checklyhq.com/v1/analytics/browser-checks/$CHECKID?metrics=availability&limit=10&page=1&quickRange=last30Days")
                          
          # Parse the API response and extract the availability
          API_AVAILABILITY=$(echo $API_RESPONSE | jq -r '.series[0].data[0].availability')

          # Compare the values and output a warning if needed
          if (( $(echo "$API_AVAILABILITY < $JWT_AVAILABILITY" | bc -l) )); then
              echo "::warning:: The API availability ${API_AVAILABILITY}% is below the JWT specified ATO standard of ${JWT_AVAILABILITY}%."
          else
              echo "The API availability ${API_AVAILABILITY}% meets or exceeds the JWT specified ATO standard of ${JWT_AVAILABILITY}%."
          fi
        shell: bash
